### ISSUE TITLE
Something is not optimal with the chapter 5 examples

### ISSUE THREAD

**Issue by kswope** [PacktPublishing/Real-Time-3D-Graphics-with-WebGL-2#1]
These examples absolutely crush my chromebook to the point of thinking I'd have to reboot.

But if I run something like this 
https://web.chemdoodle.com/demos/molgrabber-3d/
which appears to be more demanding I get completely fluid movement.

**Comment by FarhadG** [comment]
Hi, @kswope! Thanks for opening up the issue. These examples are not as optimized as ones you'd find in a library that's highly optimized for wide usage. The overall architecture/implementation have been stripped down to be able to guide users to understand core concepts.

That being said, if you'd like to build a smooth/powerful 3D rendering engine, optimizing the operations (e.g. caching matrix operations), the rendering cycle, using an ECS architecture, etc. would be very useful.

**Comment by kswope** [comment]
> Hi, @kswope! Thanks for opening up the issue. These examples are not as optimized as ones you'd find in a library that's highly optimized for wide usage. The overall architecture/implementation have been stripped down to be able to guide users to understand core concepts.

Thanks, knowing there's nothing wrong, and that optimizations can make a big difference, makes the examples even more educational.
