### ISSUE TITLE
As if clearDepth params is error

### ISSUE THREAD

**Issue by Davidyanlong** [PacktPublishing/Real-Time-3D-Graphics-with-WebGL-2#12]
in ch04/ch04_01_model-view-translation.html

line 108:    gl.clearDepth(100);

https://www.khronos.org/registry/webgl/specs/latest/1.0/ 

![image](https://user-images.githubusercontent.com/10626549/110188909-61ebd780-7e58-11eb-81ce-1294eccf7844.png)

void clearDepth(GLclampf depth) (OpenGL ES 2.0 §4.2.3, man page)
depth value is clamped to the range 0 to 1.

**Comment by packt-pradeeps** [comment]
Hi @Davidyanlong ,

Thanks for pointing this out, the issue has been fixed
