### ISSUE TITLE
Failed to execute 'attachShader'

### ISSUE THREAD

**Issue by diNicolas** [PacktPublishing/Real-Time-3D-Graphics-with-WebGL-2#2]
Hi there! 
I´m trying to load the code file examples in chapter 2 and I have the following error: 

Uncaught TypeError: Failed to execute 'attachShader' on 'WebGL2RenderingContext': parameter 2 is not of type 'WebGLShader'.

 at initProgram (ch02_01_square.html:71)
    at init (ch02_01_square.html:161).

Someone can help me?
Thanks!

**Comment by FarhadG** [comment]
Hi, @diNicolas! Thanks for your message!

I'd start by placing a `debugger` or `console` statements where the scripts are being extracted from the DOM. It seems like they're not being referenced correctly.

**Comment by diNicolas** [comment]
Fixed!, It was some weird issue with the emmet plugin and GLSL language

**Comment by itzik182** [comment]
> Hi there! I´m trying to load the code file examples in chapter 2 and I have the following error:
> 
> Uncaught TypeError: Failed to execute 'attachShader' on 'WebGL2RenderingContext': parameter 2 is not of type 'WebGLShader'.
> 
> at initProgram (ch02_01_square.html:71) at init (ch02_01_square.html:161).
> 
> Someone can help me? Thanks!

I have the same problem, can you help me please?

**Comment by itzik182** [comment]
@diNicolas I have the same problem, can you help me please?
