### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [PacktPublishing/Real-Time-3D-Graphics-with-WebGL-2#3]
**(1) ch10_01_post-process.html:354 Uncaught TypeError: Cannot read property**

> 'uNoiseSampler' of undefined
>     at render (ch10_01_post-process.html:354)
>     at events.forEach (EventEmitter.js:29)
>     at Array.forEach (<anonymous>)
>     at Clock.emit (EventEmitter.js:29)
>     at Clock.tick (Clock.js:28)
> render	@	ch10_01_post-process.html:354
> events.forEach	@	EventEmitter.js:29
> emit	@	EventEmitter.js:29
> tick	@	Clock.js:28
> 

In ch10/ch10_01_post-process.html, Lines 353 - 358:

>       // Do any additional post-process shader uniform setup here
>       if (post.uniform.uNoiseSampler) {
>         gl.activeTexture(gl.TEXTURE1);
>         gl.bindTexture(gl.TEXTURE_2D, noiseTexture.glTexture);
>         gl.uniform1i(post.uniform.uNoiseSampler, 1);
>       }
> 

Typo!
=> Change 2x 'post.uniform.uNoiseSampler' to 'post.uniforms.uNoiseSampler'

**(2) I wonder, why the texture is "mirrored" ? ...**
=> should'nt it appear as in ch07_02_textured-cube-final.html ?

**(3) Moreover I wonder, why the shaders aren't being fetched by ajax,**
since they are chapterwise all the same ... ?

**Comment by FarhadG** [comment]
Thanks for informative issue, @wolfgangvonludwigsburg! See my replies below:

1. Can you please open a PR and help improve the source code for others?
2. Not sure what you mean.
3. We tried out various formats for examples (e.g. WebPack with modules, shader plugins, etc.) but after several formats, we decided to keep things as simple as possible by co-locating as much of the code as possible to focus more on content than tools.

Looking forward to your response!

**Comment by wolfgangvonludwigsburg** [comment]
Dear Farhad,

Thanks for your attention ... !

(1)
> Open a PR ...

Sure, I'll try my best ... - if you are patient, and if you have no hurry!

It may take a while until I regain my coding-skills ...
(I recently discovered riding big motorcycles, so I delayed coding for 1 year,
but started coding again just this week.)

(2) pls have a look at the texture, the font is sort of mirrored (letters written from right to left, instead of left to right)

(3) Maybe it's simpler/more modern/ES6-like/, to manage the shader texts within grave accents
`const vertex_shader = `` ... `` `
or store the shaders non-redundantly on the file system and get them by ajax calls ...

Sorry for my humble english!
Wolfgang

**Comment by FarhadG** [comment]
Thank you, @wolfgangvonludwigsburg! No problem; take your time! I'd love more contributors to help improve the overall quality, so I'll be looking forward to your PR for both issues you've raised :)

That being said, I was using ES6 multi-line statements, however, I found that using the `script` tag approach far more feasible, as many IDEs provide you syntax highlighting. Furthermore, in IDEs, such as WebStorm, they are able the parse the code and provide many useful features. With the string literals, none of these features are provided.

In a real world project, I'd use a bundler, such as WebPack, and leverage many of the plugins available for shader parsing. But, we wanted these examples to have little-to-no dependencies.

**Comment by wolfgangvonludwigsburg** [comment]
> In a real world project, I'd use a bundler, such as WebPack,
> and leverage many of the plugins available for shader parsing.

I personally would really appreciate, if you could add an **"real world project"**
to your book's source code examples ...

- my favorite "real world project"-add-on example would be any small educational version
  of the **'Google Maps (3D Satellit view)' Mapping Tool**
  (AFAIK Google Maps intensively uses webGL, as well as 'Web Workers', but uses NO bundler !?)

Looking forward to your **Educational Maps Example**, please ...
(If I were to know, how to implement this, I would post it ..., but well, - YOU are the expert!)
