### ISSUE TITLE
Loading Sphere Model in Chapter 3 (Simplification, Improvement)

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [PacktPublishing/Real-Time-3D-Graphics-with-WebGL-2#5]
Since in Chapter 2, e.g. 07_ajax-cone.html,
**model loading by ajax** already was introduced,
one might consider to apply this accordingly in chapter 3 ...

Examples

- 01_goraud-lambert.html
- 02_moving-light.html
- 03_goraud-phong.html
- 04_sphere-phong.html

all use the **same inline defined sphere model**.
(I think there is no "learning effect" by having this model defined inline)

Assume, you stored this (inline) sphere model as "/common/models/geometries/sphere_light.json",
then, these examples could be simplified by using ajax, as follows:

Replace
```
        function initBuffers() {...}
```
by
```
        function load(filePath){

            // We return the promise so that, if needed, you can know when `load` has resolved
            return fetch(filePath)

                // Convert to a valid json
                .then(res => res.json())

                // Handle the parsed JSON data
                .then(model => {

                    const vertices  = model.vertices
                    indices         = model.indices

                    ...
                    ... ( according body content of function initBuffers() )
                    ...

                })

                // Display into the console if there are any errors
                .catch(console.error);
        }
```
and call it in init():

```
        function init() {
            initProgram()
            initLights()
            load('/common/models/geometries/sphere_light.json').then(render)
            initControls()
        }
```

**Comment by FarhadG** [comment]
Very good suggestion, @wolfgangvonludwigsburg! If you open the PR for this fix, I can approve!
