### ISSUE TITLE
Question about a comment in Camera.js

### ISSUE THREAD

**Issue by andyps** [PacktPublishing/Real-Time-3D-Graphics-with-WebGL-2#7]
There's a comment in https://github.com/PacktPublishing/Real-Time-3D-Graphics-with-WebGL-2/blob/master/common/js/Camera.js#L157.

>     // We only update the position if we have a tracking camera.
>     // For an orbiting camera we do not update the position. If
>     // Why do you think we do not update the position?

I don't quite understand this comment because it seems this code

` if (this.isTracking()) {
      const position = vec4.create();
      vec4.set(position, 0, 0, 0, 1);
      vec4.transformMat4(position, position, this.matrix);
      vec3.copy(this.position, position);
}`

doesn't change the position (so it does nothing)

**Comment by sonam-packt** [comment]
@andyps Yes as the given in the comment "we only update the position if we have a tracking camera"  if we don't then there won't be any changes in the position.
